### ISSUE TITLE
Broken shader

### ISSUE THREAD

**Issue by Kenorbrook** [keijiro/ShaderSketch0615#1]
Hi. I imported the project and tried to open the scene from the Generator folder to see what kind of shader it is. But it gives me a shader error and everything is pink.
![image](https://github.com/keijiro/ShaderSketch0615/assets/52543916/231e0974-c549-48b6-8de3-e7b9f2cac51c)

**Comment by keijiro** [comment]
Maybe it only works on Metal.

**Comment by keijiro** [comment]
Fixed (for Windows)
https://github.com/keijiro/ShaderSketch0615/commit/4424913601360273b9d2ae872cc06a5e05ace2ff
